remote_theme: fluffyemily/just-the-docs

# Enable or disable the site search
search_enabled: false

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/adameier/big-ts"
